# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [gameserverassets]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          lfs: true

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
        
      # Old: for i in  "22 /" "22 pterodactyl@sgp.potato.tf:/" "3438 pterodactyl@us.potato.tf:/" "22 pterodactyl@eu.potato.tf:/" "22 pterodactyl@eu1.potato.tf:/" "22 pterodactyl@eu2.potato.tf:/" "22 pterodactyl@aus.potato.tf:/" "22 pterodactyl@hk.potato.tf:/" "22 pterodactyl@br.potato.tf:/" "22 pterodactyl@us3.potato.tf:/"  "22 pterodactyl@us4.potato.tf:/" "22 pterodactyl@us5.potato.tf:/" "22 pterodactyl@eu4.potato.tf:/" "22 pterodactyl@eu3.potato.tf:/" "22 pterodactyl@us2.potato.tf:/" "22 pterodactyl@hk2.potato.tf:/" "2400 pterodactyl@eu3.potato.tf:/" "22 pterodactyl@eu5.potato.tf:/" "22 pterodactyl@us6.potato.tf:/" "8833 pterodactyl@pnpl.tf:/"; do a=( $i );
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          for i in  "22 /" "22 pterodactyl@sgp.potato.tf:/" "22 pterodactyl@sgp.potato.tf:/" "3438 pterodactyl@us.potato.tf:/" "22 pterodactyl@eu.potato.tf:/" "22 pterodactyl@eu3.potato.tf:/" "8833 pterodactyl@pnpl.tf:/"; do a=( $i );
          {
          rsync -a -e "ssh -p ${a[0]}" --delete --update --exclude=".*" --exclude="*.bz2" --exclude="tf_mvm_missioncycle.res" --exclude="mapcycle.txt" . ${a[1]}var/tf2server/tf/rr/
          } &
          done
          wait
          
  webdownload:
    needs: build
    runs-on: [gameserverassets]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
        with:
          lfs: true

      # Runs a set of commands using the runners shell
      - name: Install web assets
        continue-on-error: true
        run: |
          echo . -type f -not \( -name "*.bsp" -or -name "*.mp3" -or -name "*.nav" -or -name "*.res" -or -name ".bz2" \)  -exec pbzip2 -n 1 -f -k -4 {} +
          find /var/www/html/RRAssets/ -type f -not \( -name "*.pop" -or -name "*.nav" -or -name "*.res" -or -name "*.bz2" \) \( ! -regex '.*/\..*' \) -exec bzip2 -f -k {} +
      
      - name: Install web assets (hydro)
        continue-on-error: true
        run: |
          rsync -a -e "ssh -p 8833 -i ~/.ssh/tohydro" --delete --update --include="*/" --include="*.bz2" --exclude="*" /var/www/html/RRAssets/ potato@pnpl.tf:~/fastdl/
    
          
